### ISSUE TITLE
Add grouping of created photos by date

### ISSUE THREAD

**Issue by benhylau** [starlinglab/starling-integrity-api#52]
## Task Summary

📅 **Due date:** mid-Feb   
🎯 **Success criteria:** Group photos in `create-output` folder by date.  

Please add additional date sub-directory.
```
create-output/jane-doe/2022-01-24/...
                      /2022-01-25/...
                      /2022-02-11/...
create-output/mitra-moe/2022-01-24/...
                       /2022-01-25/...
```

## To Do

- [x] Add feature
- [x] Deploy this for BCN instance

**Comment by anaulin** [comment]
Are we ok adding this behavior as the default for the server? Or do we want this to be somehow configurable or switchable?

**Comment by benhylau** [comment]
I think default is ok.
