### ISSUE TITLE
Implement Opentimestamps

### ISSUE THREAD

**Issue by YurkoWasHere** [starlinglab/starling-integrity-api#61]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Research and then implement opentimestamps 

---

Read these to understand the OpenTimestamps system:
- https://en.wikipedia.org/wiki/OpenTimestamps
- https://petertodd.org/2016/opentimestamps-announcement

## Research

- [Python library](https://github.com/opentimestamps/python-opentimestamps)
- [CLI](https://github.com/opentimestamps/opentimestamps-client) in Python
- There are public verifiers like https://opentimestamps.org
- There are also public calendar servers, which are Bitcoin nodes that aggregate file hashes and commit them to the Bitcoin blockchain for free
- Calendars are not federated, but your client can ask multiple calendars to "stamp" your file (and in fact asks multiple by default)
- It takes 1 second to get a timestamp (.ots file), but it is incomplete
- To verify the timestamp against the blockchain, we have to download all the other timestamp data for the block our file was added to, which only happens after 8-9 hours
- This is called "upgrading" the timestamp, and is done by contacting calendar servers
- Upgrading can happen at any point once the block has been committed (8-9 hours after the timestamp)
- An upgraded timestamp only requires a Bitcoin node to verify the proof, not any calendar servers

## Conclusion
- If we are okay to assume calendar servers (or a mirror of them) will stick around, then the process for using OpenTimestamps is simple
	- Timestamp the file, this takes a few seconds
	- Keep the timestamp file (.ots) as part of the archive, in a way that obviously indicates which file it matches to
	- Timestamp files can be upgraded and verified at any later date
- If we don't want to assume calendar servers (or a mirror of them) will stick around:
	- Timestamp the file, this takes a few seconds
	- Keep the timestamp file in a temporary holding folder
	- Using a service or cronjob, upgrade the timestamp after 8-9 hours
	- Move the timestamp into the archive, in a way that obviously indicates which file it matches to

## To Do

- [x] How easy is it to at a future date, take the "receipt from ots" from our records, and download the merkle tree of 8-9 hrs from the ots server
	- Very easy. Just run `ots upgrade my_timestamp.ots` and the existing timestamp file will be upgraded to a full proof with all the needed data from the block

**Comment by benhylau** [comment]
Create a `opentimstamps.py` that would take in a _filepath_ and register it with a cal server then store the proof file to a path.
